version: "3.4"
services:
  development:
    image: development:latest
    environment:
      DBHOST: mysql
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - "db"
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    ports: 
      - 3306:3306

volumes:
  db-data: